name: Auto-Update Headers

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  update-headers:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get modified .txt files
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.txt' || true)
          else
            MODIFIED_FILES=$(git ls-files '*.txt')
          fi

          if [ -z "$MODIFIED_FILES" ]; then
            echo "No .txt files changed, exiting."
            exit 0
          fi

          echo "MODIFIED_FILES<<EOF" >> $GITHUB_ENV
          echo "$MODIFIED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update headers for modified files
        run: |
          timestamp=$(date -u +"%d %b %Y %H:%M UTC")
          version=$(date -u +"%Y.%m%d.%H%M.%S")

          update_headers() {
            local file=$1
            [ -f "$file" ] || return
            num_entries=$(grep -vE "^\s*$|^\s*[#!]" "$file" | tail -n +11 | wc -l | tr -d ' ')
            sed -i "s|^! Last modified: .*|! Last modified: $timestamp|" "$file"
            sed -i "s|^! Version: .*|! Version: $version|" "$file"
            sed -i "s|^! Number of entries: .*|! Number of entries: $num_entries|" "$file"
          }

          for file in $MODIFIED_FILES; do
            update_headers "$file"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.txt
          git diff --cached --quiet || (git commit -m "Auto-update headers for modified files" && git push)
