name: Update Headers in Filter Files

on:
  push:
    paths:
      - "**.txt"
  pull_request:
    types:
      - closed
    paths:
      - "**.txt"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest commit timestamp
        id: commit_time
        run: echo "TIMESTAMP=$(date -u '+%d %b %Y %H:%M UTC')" >> $GITHUB_ENV

      - name: Detect modified .txt files
        id: changed_files
        run: |
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.txt' | tr '\n' ' ')
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No modified .txt files, skipping."
            exit 0
          fi
          echo "FILES=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Update headers
        run: |
          for file in $FILES; do
            echo "Processing $file"
            VERSION_DATE=$(date -u '+%Y.%m%d.%H%M')
            ENTRY_COUNT=$(grep -Ec '^(\|\||@@)' "$file" || echo "0")

            sed -i -E "s/^!Last modified:.*/!Last modified: $TIMESTAMP/" "$file"
            sed -i -E "s/^!Version:.*/!Version: $VERSION_DATE/" "$file"
            sed -i -E "s/^!Number of entries:.*/!Number of entries: $ENTRY_COUNT/" "$file"

            echo "Updated headers for $file"
          done

      - name: Commit and push updates
        run: |
          git add $FILES
          git update-index --refresh
          if git diff --cached --exit-code; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          echo "Changes detected, committing..."
          git commit -m "Auto-update headers in text files"
          git pull --rebase
          git push
