name: Update Headers in Text Files

on:
  push:
    paths:
      - "**.txt"
  pull_request:
    types:
      - closed
    paths:
      - "**.txt"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest commit timestamp
        id: commit_time
        run: echo "timestamp=$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Detect all .txt files
        id: changed_files
        run: |
          MODIFIED_FILES=$(git ls-files '*.txt')
          echo "files=$MODIFIED_FILES" >> $GITHUB_ENV

      - name: Update headers
        run: |
          for file in ${{ env.files }}; do
            echo "Processing $file"
            VERSION=$(grep -oP '^# Version: \K[0-9]+\.[0-9]+\.[0-9]+' "$file" || echo "1.0.0")
            IFS='.' read -r major minor patch <<< "$VERSION"
            NEW_VERSION="$major.$minor.$((patch + 1))"
            ENTRY_COUNT=$(grep -cE '^\|\| |^@@' "$file" || echo "0")
            COMMIT_HASH=$(git rev-parse --short HEAD)

            # Replace headers
            sed -i "s/^# Last Modified: .*/# Last Modified: ${{ env.timestamp }}/" "$file"
            sed -i "s/^# Version: .*/# Version: $NEW_VERSION/" "$file"
            sed -i "s/^# Entry Count: .*/# Entry Count: $ENTRY_COUNT/" "$file"
            sed -i "s/^# Commit: .*/# Commit: $COMMIT_HASH/" "$file"

            touch "$file" # Force Git to detect the change
            echo "Updated headers for $file"
          done

      - name: Check for changes
        id: check_diff
        run: |
          git add -A
          git update-index --refresh
          if git diff --cached --exit-code; then
            echo "No real changes detected, but ensuring headers are correct."
            git commit --amend --no-edit || echo "No changes to amend."
          else
            echo "Changes detected, committing..."
            git commit -m "Auto-update headers in text files"
          fi
          git pull --rebase
          git push --force
