name: Auto-Update Headers

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  update-headers:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect modified .txt files
        id: detect-files
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.txt' || true)
          else
            MODIFIED_FILES=$(git ls-files '*.txt')
          fi
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No .txt files changed, exiting."
            echo "modified=false" >> "$GITHUB_OUTPUT"
          else
            echo "FILES_MODIFIED=$MODIFIED_FILES" >> $GITHUB_ENV
          fi

      - name: Update headers in modified files
        if: env.FILES_MODIFIED
        run: |
          timestamp=$(date -u +"%d %b %Y %H:%M UTC")
          version=$(date -u +"%Y.%m%d.%H%M.%S")

          update_headers() {
            local file=$1
            [ -f "$file" ] || return
            num_entries=$(grep -vE "^\s*$|^\s*[#!]" "$file" | tail -n +11 | wc -l | tr -d ' ')
            sed -i "s|^! Last modified: .*|! Last modified: $timestamp|" "$file"
            sed -i "s|^! Version: .*|! Version: $version|" "$file"
            sed -i "s|^! Number of entries: .*|! Number of entries: $num_entries|" "$file"
          }

          for file in $FILES_MODIFIED; do
            update_headers "$file"
          done

      - name: Commit and push updates
        if: env.FILES_MODIFIED
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILES_MODIFIED
          if git diff --cached --quiet; then
            echo "No header changes detected."
          else
            git commit -m "🤖 Auto-update headers for modified blocklists"
            git push
          fi
